### ISSUE TITLE
Base docker image with flakes support

### ISSUE THREAD

**Issue by offlinehacker** [xtruder/debian-nix-devcontainer#3]
Currently the default base image is built with latest stable nix. Since more and more users use flakes and stable nix does not have flakes support a new docker image should be created.

Create a separate tagged image that has flakes support. Also create an example, so developers know how to use that image.

**Comment by offlinehacker** [comment]
Github actions now build image with flakes support.

**Comment by meicale** [comment]
It seems that it needs updating. Flakes are quite useful, would you mind update this repo based on flakes? Thx!
