### ISSUE TITLE
How to clean nix store properly

### ISSUE THREAD

**Issue by Rizary** [xtruder/debian-nix-devcontainer#4]
Docker desktop maximum storage is 250G. However, we can increase it by using the following step: https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk

How do we handle nix storage in this regard? I mean, should we call `nix-collect-garbage` before we run `nix develop`?

**Comment by offlinehacker** [comment]
There are multiple ways to clean I can think of
- nix-collect-garbage
- stop devcontainer, delete nix volume associated with devcontainer and rebuild

What I usually do is just delete stale nix volumes

**Comment by Rizary** [comment]
Thanks!
